sudo: required

language: go

services:
  - docker

go:
  - "1.10"

before_install:
  - go get github.com/adlio/trello
  - go get github.com/nlopes/slack

addons:
  apt:
    packages:
      - docker-ce

script:
  - go test -v
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build main.go; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker build -t dhruvdhir/rudolph:1.0.$TRAVIS_BUILD_NUMBER -t dhruvdhir/rudolph:latest .; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "$password" | docker login -u "$username" --password-stdin; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker push dhruvdhir/rudolph:latest; fi' 
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker push dhruvdhir/rudolph:1.0.$TRAVIS_BUILD_NUMBER; fi'